const GLOSSARY_DB = {
    "ācārya": "Spiritual preceptor, one who teaches by example.",
    "acintya": "Inconceivable.",
    "acintya-bheda-abheda-tattva": "Fundamental truth of the Supreme Person, who is inconceivably non-different from (abheda) and different from (bheda) His potencies.",
    "acintya-śakti": "Śrī Bhagavān’s inconceivable potency.",
    "acyuta": "Infallible.",
    "adharma": "Irreligion.",
    "adhibhautika": "Suffering caused by other living beings.",
    "adhibhūta": "All gross phenomena.",
    "adhiyajña": "In-dwelling Supersoul, who inspires the living entities to perform sacrifice and awards the results of their prescribed duty.",
    "adhokṣaja": "The Lord who is beyond the cognition and perception of the material senses.",
    "ādi": "Beginning, first.",
    "aditi": "Wife of Prajāpati Kaśyapa; mother of the twelve Ādityas. Her eldest son was Indra and her youngest was Upendra, or Vāmanadeva, the dwarf incarnation of the Lord.",
    "ādityas": "The twelve sons of Aditi and Kaśyapa.",
    "advaitavādī": "Follower of non-dualism, or monism (advaitavāda), as propounded by Śrī Śaṅkara Ācārya.",
    "agni": "Presiding deity of fire and son of Brahmā.",
    "ahaṅgraha-upāsaka": "One who takes himself as the object of worship, believing that the jīva and Bhagavān are ultimately the same. Literally, aham–‘myself’, graha–‘accepting’, upāsanā–‘worship’.",
    "aikāntika": "One-pointed, unflinching.",
    "aikāntik ā-niṣṭhā": "One-pointed faith.",
    "airāvata": "Lord Indra’s elephant carrier.",
    "aiśvarya": "(1) Majestic opulence (2) Derived from the word īśvara. In regard to bhakti, this refers to devotion that is inspired by the majesty of Bhagavān, rather than by His mādhurya (sweetness). It especially applies to His feature as Nārāyaṇa. Aiśvarya restricts the intimacy between Bhagavān and His devotees.",
    "akiñcana": "(1) Without material possessions (2) One whose sole possession is service to Kṛṣṇa.",
    "amara-koṣa": "An ancient authoritative Sanskrit thesaurus.",
    "aṃ śa": "Portion, or expansion, of Śrī Kṛṣṇa.",
    "ānanda": "Transcendental bliss (See hlādinī-śakti).",
    "ānandamaya": "The fifth stage of consciousness, awarenes of service to Rādhā and Kṛṣṇa (13.5).",
    "ananta-rūpa": "Unlimited forms.",
    "ananya": "Literally, ‘without another’; exclusive, one-pointed.",
    "ananyā-bhakti": "Exclusive devotion, unmixed with any other desire, in which one’s sole motivation is to please Bhagavān.",
    "ananya-yoga": "Bhakti unmixed with dependence on speculative knowledge, fruitive work or austerities.",
    "anartha": "Unwanted desires, activities or habits that are likened to weeds hindering one’s advancement in bhakti.",
    "anartha-nivṛtti": "Clearance of anarthas, the fourth stage in the development of the creeper of bhakti.",
    "anātmā": "Not soul; inert matter.",
    "aṅga": "(1) Limb, division, part (2) The various practices of devotion such as hearing and chanting.",
    "aṇimā": "Small like an atomic particle.",
    "anīśvaram": "Concept that the cosmic manifestation has no Īśvara (controller) but has come about by accident (16.8).",
    "annamaya": "First of the five stages of consciousness in which everything is seen in terms of anna (food-grains) (13.5).",
    "antaryāmī": "In-dwelling witness, the Supersoul, who guides the activities of all living entities.",
    "antya": "Last.",
    "antyaja": "(1) Of lower birth (2) Outcaste.",
    "apāna": "Out-going breath.",
    "aparā": "Not transcendental, inert matter, material nature.",
    "aparādha": "(1) That which undermines arādhana, or devotion (2) An offence, or an impediment to bhakti. Arcana-dīpikā lists 64 sevā-aparādhas, 10 nāmā-aparādhas and 10 dhāmā-aparādhas to avoid.",
    "aprākṛta": "Non-material, transcendental.",
    "āptakāma": "One whose desires have been fulfilled; a self-satisfied soul.",
    "arcana": "Worship.",
    "arjuna": "(1) Śrī Kṛṣṇa’s intimate friend and devotee to whom He spoke the Bhagavad-gītā (2) The Nara portion of the Nara-Nārāyaṇa sages, Śrī Kṛṣṇa being the Nārāyaṇa portion (3) An eternal liberated soul who always serves Śrī Kṛṣṇa out of love.",
    "ārta": "One who approaches Bhagavān in a mood of distress (7.16).",
    "artha": "Wealth, the second material goal of human life (See dharma, kāma and mokṣa).",
    "artha-śāstra": "Scriptures on economic development.",
    "ārya-ṛṣis": "Ancient, most noble sages who have seen the Truth.",
    "āsakti": "Deep attachment, especially to Bhagavān and His associates; the sixth stage in the development of the bhakti creeper awakened after ruci (taste for bhajana) matures.",
    "āsana": "(1) Seat (2) Sitting posture for meditation.",
    "asita": "The name of an ancient sage who was an authority on the Vedas.",
    "āśrama": "(1) Stage of life, either student (brahmacārī), householder (gṛhastha), retired (vānaprastha) or renounced (sannyāsa) (2) Hermitage.",
    "āśraya": "Repository of love for Kṛṣṇa, i.e., His devotee.",
    "aṣṭāṅga-yoga": "Eightfold yoga process, consisting of yama (control of the mind and senses), niyama (following rules and regulations of yoga practice), āsana (bodily postures), prānāyama (breath control), pratyāhāra (withdrawal of the mind from sensory perception), dhāraṇā (steadying the mind), dhyāna (meditation) and samādhi (trance).",
    "aśvamedha-yajña": "Elaborate sacrifice performed by brāhmaṇas on behalf of powerful kings, wherein a horse is sacrificed into the sacred fire and then brought back to life.",
    "aśvattha": "Type of pīpala tree (10.26).",
    "aśvinī-kumāras": "Physicians of the demigods.",
    "atirathī": "Warrior who can face unlimited opponents.",
    "ātmā": "(1) Soul (2) Supersoul (3) Intelli-gence (4) Mind (5) Body (6) Senses.",
    "ātma-tattva": "Categorical knowledge of the nature of the soul.",
    "avatāra": "Śrī Kṛṣṇa Himself or His plenary portion who descends from the transcendental realm into this material creation for the deliverance of conditioned souls.",
    "avidyā": "Nescience, or culture of material knowledge, considering such knowledge to be the all-in-all.",
    "avyabhicāra": "Unfailing;refers to pure devotion.",
    "avyakta": "(1) Unmanifest (2) Beyond the perception of the senses.",
    "avyaya": "Imperishable.",
    "bahiraṅg ā-śakti": "The Lord’s exter-nal, or material, potency, also known as māyā. It is the medium by which the material world is created, as well as all affairs pertaining to it.",
    "baladeva vidyābhūṣaṇa": "Chief disciple of Śrī Viśvanātha Cakravartī Ṭhākura and author of Govinda-bhāṣya, the Gauḍīya Vaiṣṇava commentary on Vedānta-sūtra. He is thus aptly named Gauḍīya-vedāntācārya.",
    "bhagavān": "The Supreme Lord, complete in six opulences: beauty, wealth, strength, fame, knowledge and renunciation. Literally, vān–‘possessor’, bhaga–‘opulence’.",
    "bhāgavatam": "See Śrīmad-Bhāgavatam.",
    "bhāgavatāmṛtam": "A book by Śrīla Sanātana Gosvāmī. Literally, ‘the nectarean essence of Śrīmad-Bhāgavatam’.",
    "bhagavat-kathā": "Narrations of Śrīmad-Bhāgavatam or the instructions of Śrī Bhagavān, as in Śrīmad Bhagavad-gītā.",
    "bhagavat-prema": "Love for the all-opulent Personality of Godhead.",
    "bhagavat-tattva": "Categorical knowledge of Bhagavān; the principles taught by Śrī Bhagavān.",
    "bhajana": "(1) Service (2) Spiritual practice, especially hearing, chanting, remembering and meditating on the holy name, form, qualities and pastimes of Śrī Kṛṣṇa.",
    "bhakta": "Devotee;one devoted to bhakti-yoga and one’s worshipable deity.",
    "bhakti": "Derived from the root bhaj (to serve). It is the performance of activities meant exclusively for the pleasure of the Supreme Lord Śrī Kṛṣṇa that are done in a favourable spirit, saturated with love, devoid of other desires, and not covered by karma and jñāna is called bhakti (Bhakti-rasāmṛta-sindhu 1.1.12).",
    "bhakti-devī": "Presiding deity of bhakti-yoga.",
    "bhakti-miśra-jñāna": "Knowledge mixed with devotion, with knowledge predominating.",
    "bhakti-rasāmṛta-sindhu": "A book by Śrīla Rūpa Gosvāmī meaning ‘the nectarean ocean of the mellows of devotion’, which explains the science of bhakti-yoga.",
    "bhakti-yoga": "Path of spiritual realization through devotional service to Bhagavān.",
    "bhāva": "(1) Special manifestation of śuddha-sattva (2) The essence of the cognizance potency and the pleasure-giving potency (3) Eighth stage in the development of the creeper of bhakti; likened to the first rays of the sun of prema, the highest stage of love for Kṛṣṇa.",
    "bhāvānuvāda": "Translation that takes into account specific subtleties.",
    "bhīṣma-parva": "The eighteen chapters of the Mahābhārata that comprise Śrīmad Bhagavad-gītā.",
    "bhṛgu": "One of the seven sages, born from the mind of Lord Brahmā.",
    "bhūta-bhāvana": "Maintainer of all manifestations.",
    "brahma": "(1) Derived from bṛḥ meaning ‘expanded’, or ‘great’; the general meaning is spirit (2) The living entity (3) The mind (4) The Supersoul (5) The impersonal aspect of the Supreme Lord (6) Bhagavān Himself.",
    "brahmā": "Creator of the material universe who is the presiding deity of the quality of passion. He is the original spiritual master of the Brahma-Mādhva sampradāya.",
    "brahma-bhūta": "Brahma realized; the state wherein one experiences bliss, free from hankering and lamentation (18.54).",
    "brahmacarya": "Literally, ‘spiritual cultivation’; the first āśrama, or stage of life, in the varṇāśrama system; celibate student life.",
    "brahma-jñāna": "Knowledge of brahma.",
    "brahma-loka": "Abode of Lord Brahmā, which is within this material universe.",
    "brāhmaṇa": "(1) One who realizes brahma; one of the four varṇas (2) Social divisions, in the varṇāśrama system; priest or teacher.",
    "brahmānanda": "Bliss experienced by one situated in brahma.",
    "brahmarṣi": "Sages situated in brahma realization.",
    "brahmāstra": "The most powerful weapon in Vedic military science (superior to nuclear weapons). It is released by mantra and kills only the person whose name is uttered in conjunction with the mantra.",
    "brahma-sūtra": "(Also known as Vedānta-sūtra) The aphorisms of Vedānta offer a complete systematic exposition of Vedic revelation in the form of terse aphorisms (sūtras). Śrīmad-Bhāgavatam, composed by Śrīla Vyāsadeva, is the natural commentary on Vedānta-sūtra.",
    "brahma-svarūpa": "The form of Śrī Kṛṣṇa, whose bodily effulgence is the brahma-jyoti.",
    "brahma-tattva": "Categorical knowledge of brahma.",
    "brahmavāda": "Doctrine of impersonalism, the goal which is to merge into the Supreme Lord’s effulgence.",
    "brahma-vettā": "One who has realized brahma.",
    "bṛhad-āraṇyaka śruti": "Upaniṣad containing important verses relevant to Gauḍīya Vaiṣṇava philosophy.",
    "buddhi": "(1) Intelligence (2) Ability to discern subtle meanings.",
    "buddhism": "Philosophy introduced by Śākyasiṃha Buddha that expounds voidist concepts of the Absolute Truth known as śūnyatā or śūnyavāda.",
    "caitanya-śikṣāmṛta": "A book by Śrīla Bhaktivinoda Ṭhākura, meaning ‘nectarean instructions of Śrī Caitanya’. It presents an elaborate description of the progression of bhakti.",
    "candra": "Moon-god.",
    "catuḥ-ślokī gītā": "Essence of Bhāgavad-gītā (10.8–11). The four verses that summarize the three Vedic divisions of sambandha (relationship), abhidheya (means) and prayojana (the ultimate goal).",
    "cāturmāsya": "The four months during the rainy season (August to November) in which the practice of certain prescribed austerities is very potent for spiritual development.",
    "cit": "(1) Spirit (2) Consciousness (3) Pure thought.",
    "cit-jagat": "All-conscious spiritual world.",
    "citraratha": "Chief among the Gandharvas and a representation of Śrī Kṛṣṇa’s opulence.",
    "cit-śakti": "Potency that relates to the cognizant aspect of the Supreme Lord. By this śakti, He knows Himself and causes others to know Him. Knowledge of the Absolute Reality is only possible with the help of this potency.",
    "citta": "Heart, thoughts, mind and consciousness.",
    "dānavas": "Demons.",
    "darśana": "(1) Behold, or meet. It is used in reference to beholding either the deity or advanced devotees. (2) Doctrine, or philosophical system, as in Vedānta-darśana.",
    "demigods": "(1) Celestial deities (2) Godly beings situated in the higher planets who are endowed with great piety and who have tremendous life spans and whose mental and physical prowess is superior to humans. They are entrusted with specific powers for the purpose of universal administration.",
    "deva": "Demigods.",
    "deva-deva": "God of gods.",
    "devakī-nandana": "Son of Devakī, Śrī Kṛṣṇa.",
    "devala": "A sage, who was an authority on the Vedas. He was the elder brother of Dhaumya (the priest of the Pāṇḍavas).",
    "devarṣi nārada": "Sage (ṛṣi) amongst the demigods (devas). Literally, nāra–‘God’, dā–‘giver’; a great devotee of Śrī Kṛṣṇa who spreads His glories throughout the universe.",
    "deveśa": "Lord of the demigods, a name for Śrī Kṛṣṇa.",
    "devī": "Demigoddess.",
    "dhāma": "Abode of Śrī Bhagavān in which He appears and enacts His divine pastimes.",
    "dhanañjaya": "A name awarded to Arjuna who accumulated great wealth while conquering the many kings of northern Bhārata (India) in preparation for the rājasūya-yajña of Mahārāja Yudhiṣṭhira. Literally, ‘winner of wealth’.",
    "dhāraṇā": "Concentration of the mind, the sixth step in aṣṭāṅga-yoga.",
    "dharma": "From the verbal root dhṛ, to sustain. Literally, ‘that which sustains’; (1) The natural, characteristic function of a thing; that which cannot be separated from its nature (2) Religion in general (3) The socio-religious duties prescribed in the scriptures for different classes of persons in the varṇāśrama system (4) One’s fixed occupation in relation to Śrī Kṛṣṇa.",
    "dhṛtarāṣṭra": "Literally, dhṛta–‘holds on to’, rāṣṭra–‘the kingdom’. He was the son of Ambikā and Vyāsadeva; brother of Pāṇḍu and Vidura. Dhṛtarāṣṭra, was born blind. His one hundred sons, headed by Duryodhana, led the armies that opposed the Pāṇḍavas.",
    "dhyāna": "Meditation, the seventh stage of aṣṭāṅga-yoga.",
    "dīkṣā": "Initiation from a spiritual mas-ter. In Bhakti-sandharbha (Anucceda 283) Śrīla Jiva Gosvāmī defines dīkṣā: learned exponents of the Absolute Truth declare that the process by which the guru imparts divya-jñāna to the disciple and eradicates all sins is known as dīkṣā.",
    "dravya-yajña": "The sacrifice of giving material possessions in charity.",
    "droṇa, droṇācārya": "Commander of the Kaurava army.",
    "drupada": "In the Mahābhārata War, Drupada was one of the commanders of the Pānḍava army and was killed by Droṇa. Dṛṣṭadyumna, Drupada’s son avenged his death.",
    "durgā": "Literally, dur–‘difficult’, gā–‘to get out’, i.e. a prison. The material world is like a prison for the rebellious conditioned souls. Durgā is mother nature, the goddess of material nature and consort of Mahādeva Śiva.",
    "duryodhana": "Literally, dur–‘bad’, yodhana– ‘fighter’. In the Mahābhārata War, Duryodhana was the leader of the Kauravas. He is a partial incarnation of Kali.",
    "dvāpara-yuga": "One of the four ages: Satya, Treta, Dvāpara and Kali. In Dvāpara-yuga people attained perfection by performing excellent worship of the deity incarnation of the Lord.",
    "ekādaśī": "Eleventh day of the lunar fortnight. On that day, scripture prescribes fasting from grains, beans and other foodstuffs so that the sādhaka can totally immerse himself in activities of pure bhakti. Ekādaśī is referred to as the mother of devotion.",
    "gandharvas": "Singers and musicians from the higher planets.",
    "gaṇeśa": "Elephant scribe of Vyāsadeva.",
    "gaṅgā": "The Ganges, the river of divine water that falls from the spiritual sky to this universe.",
    "gargācārya": "Guru of Kṛṣṇa’s father, Vasudeva. He performed Śrī Kṛṣṇa’s name-giving ceremony in Gokula and wrote Garga-saṃhitā, a famous literature describing the pastimes of Śrī Kṛṣṇa.",
    "gautama": "A sage and the author of nyāya-darśana (the philosophy of logic), which is one of the six systems of philosophy.",
    "gāyatrī": "Literally, trī–‘that which gives deliverance’, gāya–‘through singing’. Gāyatrī is the mother of the Vedas. Brahma-saṃhitā states that Lord Brahmā first heard the flute-song of Kṛṣṇa through his eight ears as the syllable oṃ, then, when he chanted it himself, it became gāyatrī, by which he became enlightened. Thus he became initiated as a brāhmaṇa.",
    "gītā": "Literally, ‘song’. Śrīmad Bhagavad-gītā.",
    "gītā-bhūṣaṇa": "Śrīla Baladeva Vidyābhūṣaṇa’s Sanskrit commentary on Śrīmad Bhagavad-gītā. Literally, ‘a decoration of the Gītā’.",
    "gopāla-tāpanī śruti": "An Upaniṣad that sweetly delineates the truths of Śrī Śrī Rādhā-Kṛṣṇa.",
    "gopī": "A transcendental cowherd maiden of Vraja.",
    "gosvāmī": "(1) One who is the master of one’s senses, detached from material elements (2) One in the renounced order of life.",
    "gotra": "Seminal line from the prajāpatis and forefathers.",
    "gṛhastha": "Householder.",
    "guḍākeśa": "A name for Arjuna meaning ‘conqueror of ignorance’.",
    "guṇa": "Binding force. The three qualities of material nature bind the living entity. There are three guṇas: goodness (sattva), passion (rajas) and darkness, or ignorance (tamas). Literally, ‘rope’ (See Chapter 14).",
    "guṇa-avatāras": "The three primary presiding deities of the three binding forces. Brahmā, Viṣṇu and Śiva are together known as tri-mūrti.",
    "guṇī -bhūtā-bhakti": "Devotion that is predominated by the modes of nature.",
    "guru": "(1) Spiritual master (2) Guru means ‘heavy with realization of divine knowledge’. By steadiness, the guru anchors the disciple’s restless mind from the turbulent waters of the material energy. Literally, gu–‘ignorance’, ru–‘he who dispels’. One who is guru will dispel all ignorance.",
    "guru-dakṣiṇā": "Wealth or gifts offered to the guru by the disciple.",
    "guru-paramparā": "System of disciplic succession in which divine knowledge is transmitted from śrī guru to a fully surrendered disciple.",
    "hari-bhakti-vilāsa": "A book that describes many aspects of Vaiṣṇava life. It was written by Śrīla Sanātana Gosvāmī and Śrīla Gopāla Bhaṭṭa Gosvāmī under the direct instruction of Śrī Caitanya Mahāprabhu and is divided into twenty sections (vilāsas).",
    "hari-nāma": "The names of Śrī Kṛṣṇa: Hare Kṛṣṇa, Hare Kṛṣṇa, Kṛṣṇa Kṛṣṇa, Hare Hare, Hare Rāma, Hare Rāma, Rāma Rāma, Hare Hare. These sixeen names destroy all the bad qualities of the age of Kali (Kali-santaraṇa Upaniṣad).",
    "ha ṭha-yoga": "The yoga process of practising different bodily postures in order to render the body supple. It is the third portion of the process of aṣṭāṅga-yoga.",
    "hlādinī-śakti": "Bliss potency or the internal, spiritual potency, which is dominated by bliss, personified as Śrīmati Rādhārāṇī. Hlādinī is the śakti that arouses ānanda (bliss) in the heart of Śrī Śyāma. Although Kṛṣṇa Himself is the reservoir of all pleasure, through His hlādini potency, He relishes transcendental bliss.",
    "hṛṣīkeśa": "Literally, īśa–‘lord’, hṛṣīka–‘of the senses’. A name for Kṛṣṇa meaning ‘one who turns the senses of His devotees towards Himself and those of the non-devotees away’.",
    "īkṣvāku": "The son of Vivasvān the sun-god; Earth’s first king.",
    "indra": "King of heaven.",
    "īśa": "Controller. Sometimes refers to Viṣṇu and other times to Rudra.",
    "īśvara": "Supreme Controller, Bhagavān. Also a name for the Supersoul (15.15).",
    "jaḍa": "Inert, dull.",
    "jaḍa-vādī": "One who adheres to the view (vāda) that there is nothing but matter (jaḍa); an atheistic scientist.",
    "jagad-guru": "Universal guru.",
    "jagat-pati": "Master of the universe.",
    "jainism": "A religious movement begun many hundreds of years ago by King Arhat. The strict followers of Jainism idealistically try to emulate Mahārāja Ṛṣabhadeva by practising non-violence and by not using vehicles. Ṛṣabha was an avatāra of Śrī Kṛṣṇa, whose history is described in the Fifth Canto of Śrīmad-Bhāgavatam.",
    "jalpa": "Logical argument that utilizes continuous fault-finding of the opponent’s statements to establish one’s own opinion.",
    "jamadagni": "A brāhmaṇa who possessed a wish-fulfilling cow. He was slain by a group of kṣatrīyas for the sake of the cow, and his son, Paraśurāma, an incarnation of the Lord, took revenge by slaying the kṣatrīya population of the world.",
    "janamejaya": "The son of King Parīkṣit.",
    "janārdana": "Name of Bhagavān meaning ‘one who thrills the hearts of mankind’.",
    "japa": "The chanting of the holy name on a garland of 108 prayer beads.",
    "jīva": "Living entity; soul.",
    "jīva-śakti": "(See taṭasthā-śakti).",
    "jīva-tattva": "Categorical knowledge of the living entity, his nature and his position.",
    "jīvātmā": "The spirit soul (See jīva).",
    "jñāna": "(1) Knowledge; that which helps one know something (18.18) (2) Knowl-edge that leads to impersonal liberation, which is based on the soul’s distinction from matter and its identity with brahma (3) Transcendental knowledge of one’s relationship with Kṛṣṇa.",
    "jñāna-miśrā-bhakti": "Devotion mixed with knowledge, devotion predominating.",
    "jñāna-sannyāsa": "Renunciation of knowledge.",
    "jñāna-yajña": "Sacrifice in the form of deliberation on spiritual nature.",
    "jñāna-yoga": "Path of spiritual realization through a philosophical search for truth.",
    "jñānī": "One in search of knowledge, either impersonal or personal.",
    "jñeya": "Object of knowledge.",
    "kaivalya": "Oneness, or mukti.",
    "kali-yuga": "Present age of quarrel and hypocrisy. It lasts for 432,000 years, of which approximately five thousand have now passed (Refer to Śrīmad-Bhāgavatam Canto 12 Chapter 2).",
    "kalpa": "One day in the life of Lord Brahmā. It is equivalent to one thousand catur-yugas. Each catur-yuga is one cycle of the four yugas: Satya, Dvāpara, Tretā and Kali, totalling 4,320,000,000 years (8.17).",
    "kāma": "(1) Desire (2) Sense enjoyment (3) The third of the four goals of human society. Those who have no desire other than for the satisfaction of the gross senses aspire for such pleasure. Their puruṣārtha is known as kāma (See dharma, ārta and mokṣa).",
    "kāmadhenu": "A cow who can fulfil all desires.",
    "kāmya-karma": "Fruitive activities.",
    "kandarpa": "Cupid, the indirect cause of the birth of living beings. Kandarpa is Śrī Kṛṣṇa’s representative as a progenitor (10.28).",
    "karma": "(1) Work prescribed in the Vedas (2) Activity in general (3) Pious activity performed with Vedic guidance leading to material gain in this world or to the higher planets after death (See prescribed duty).",
    "karma-codanā": "Impetus to perform action (18.18).",
    "karma-kāṇḍa": "Division of the Vedas that involves the performance of ceremonial acts and sacrificial rites directed towards material benefits or liberation.",
    "karma-miśrā-bhakti": "Devotion mixed with the performance of prescribed duty, with devotion predominating.",
    "karma-pradhānī-bhūtā-bhakti": "Devotion mixed with the performance of prescribed duty, with devotion predominating. (This is a different term for karma-miśrā-bhakti.)",
    "karma-sannyāsa": "Renunciation of fruitive work.",
    "karma-yajña": "Sacrifice performed for fruitive gain.",
    "karma-yoga": "Path of spiritual realization in which the fruit of one’s work is offered to Bhagavān.",
    "karmī": "One who performs karma in accordance with Vedic injunctions.",
    "kauravas": "Some of the descendants of King Kuru who fought on the one side at Kurukṣetra.",
    "kena upaniṣad": "The Upaniṣad that is filled with questions relevant to the ultimate purpose of human life. It is known as the ‘Why?’ Upaniṣad.",
    "kevalā-bhakti": "Exclusive devotion in which one has no attachment to anyone but Bhagavān.",
    "khasa": "Mongolians, Chinese and certain races north of India.",
    "kinnara": "A kind of demigod who plays musical instruments and sings with the Gandharvas.",
    "kīrtana": "Chanting of the names of Bhagavān; the most important limb of the nine limbs of bhakti.",
    "kleśa-ghnī": "Literally, ‘destroyer of misery’.",
    "kriyā": "Activity.",
    "kṛṣṇa": "Śrī Bhagavān, the Supreme Personality of Godhead.",
    "kṛṣṇacandra": "Śrī Kṛṣṇa whose transcendental body bears twenty-four-and-a-half moons.",
    "kṛṣṇa-prema": "Pure love for Kṛṣṇa.",
    "kṛṣṇa-tattva": "Categorical knowledge about the unique position, qualities, etc., of Śrī Kṛṣṇa.",
    "kṣara": "Perishable.",
    "kṣatriya": "One of the four varṇas in the varṇāśrama system, which refers to an administrator or a warrior. Literally, kṣi–‘destruction’, tṛ–‘deliverance’.",
    "kṣetra": "Field of the body (13.1).",
    "kṣetra-jña": "Knower of the field. The partial kṣetra-jña is the living entity; the complete kṣetra-jña is Paramātmā (13.1).",
    "kṣīrodakśāyī viṣṇu": "Śrī Kṛṣṇa’s Viṣṇu expansion who lies within an ocean of kṣīra (milk). As the Paramātmā, He enters within every atom and the heart of all beings as a witness, and gives remembrance, knowledge and forgetfulness.",
    "kurukṣetra": "‘Field of the Kurus’, an ancient holy place where Paraśurāma performed penances of atonement. It is still visited to this day (especially when there is an eclipse), for shelter from inauspicious effects.",
    "kūṭa-stha": "Firmly situated in one’s own transcendental position, free from any sensual agitation.",
    "kuvera": "Treasurer of the demigods, god of wealth.",
    "līlā": "Divine sportive pastimes of the Supreme Lord or His eternal associates.",
    "līlā-avatāra": "Kṛṣṇa’s pastime manifestations eg. Nṛṣiṃha, Varāha and Kūrma.",
    "līlā-puruṣottama": "Śrī Kṛṣṇa, the Supreme Person whose pastimes are unsurpassed by any of His other incarnations.",
    "mādhurya": "With sweetness, or beauty. It refers to devotion inspired by attraction to Bhagavān’s sweet and intimate feature as a beautiful young cowherd boy and to the greatest exchange of love between Kṛṣṇa and His devotees.",
    "mādhurya-kādambinī": "Book written by Śrī Viśvanātha Cakravartī Ṭhākura, meaning ‘cloud-bank of sweetness’. It describes the eight progressive stages of bhakti, culminating in prema.",
    "madhusūdana sarasvatī": "1540–1632;formerly a monist but became attracted to Gauḍīya Vaiṣṇavism. He was the author of Gītā-gūḍhārtha-dīpikā.",
    "madhva": "The chief ācārya of the Brahmā sampradāya who established the doctrine of dvaita-vāda, which emphasizes the eternal distinction between the living entity and the Supreme Lord.",
    "mahā-bāho": "O mighty-armed one.",
    "mahā-bhāgavata": "Topmost devotee of the Supreme Lord.",
    "mahābhārata": "Epic describing the ancient history of the world leading up to the battle of Kurukṣetra. It was composed by Śrīla Kṛṣṇa Dvaipāyana Vyāsadeva for the benefit of the people of this age of Kali, who have no interest in philosophy. Śrīmad Bhagavad-gītā is strategically placed in the midst of this epic.",
    "mahājana": "Spiritual authority; one who truly understands religious prin-ciples; the twelve principal mahājanas are identified in the Śrīmad-Bhāgavatam (6.3.20) as Lord Brahmā, Bhagavān Nārada, Śivajī, the four Kumāras, Kapiladeva, Svāyambhuva Manu, Prahlāda Mahārāja, Janaka Mahārāja, Grandsire Bhīṣma, Balī Mahārāja, Śukadeva Gosvāmī and Yamarāja.",
    "mahāmāyā": "(See māyā-śakti).",
    "mahā-puruṣa": "Liberated soul, specifically a great devotee, who is detached from the material world.",
    "mahārathī": "Warrior who can face ten thousand opponents at one time.",
    "maharṣi": "Seer of the Truth. He has seen the worshipable deity of one’s mantra.",
    "mahā-tattva": "The aggregate of five gross and three subtle material energies is called pradhāna. When it is activated by the glance of Mahā-Viṣṇu it becomes known as mahā-tattva.",
    "mahātmā": "Magnanimous person, or great soul. It is a title of respect offered to those elevated in spiritual consciousness.",
    "mahā-viṣṇu": "Another name of Karaṇodakaśayī Viṣṇu, a plenary portion of Śrī Kṛṣṇa who creates the cosmic manifestion, consisting of countless universes.",
    "maheśvara": "Supreme Controller; it sometimes refers to Śambhu Śiva and sometimes to Bhagavān Śrī Kṛṣṇa.",
    "manomaya": "Third of the five stages of consciousness in which one is conscious of the mind (13.5).",
    "mantra": "Literally, man–‘mind’, tra–‘delivering’.",
    "manus": "Prajāpatis (universal progenitors) delegated by Śrī Bhagavān to generate human population. There are fourteen manus in one day of Brahmā, the present manu being Vaivasvata Manu.",
    "manuṣya-loka": "Middle planetary systems, specifically this earth planet.",
    "manvantara": "The reign of one manu.",
    "mārga-śīrṣa": "November–December; the best of months because grains are collected from the field at this time.",
    "marīci": "Controlling deity of the fifty kinds of winds in the universe.",
    "maruts": "Wind-gods.",
    "maṭha": "A temple of the Lord with attached living quarters for brahmacārīs and sannyāsīs; a monastery.",
    "maudgalya gotra": "Lineage descending from the sage Mudgala.",
    "māyā": "Literally, mā–‘not’, yā–‘this’. In other words ‘that which is not’; an illusion (See māyā-śakti).",
    "māyā-śakti": "External energy of Bhagavān, which influences the living entities to accept the false egoism of being independent enjoyers of this material world. There are three functions of māyā: pradhāna, which creates the illusory designations of the living entity; avidyā, which superimposes these designations; and vidyā, which removes them.",
    "māyāvāda": "Doctrine of illusion. This theory, advocated by the impersonalist followers of Śaṅkarācārya, holds that Bhagavān’s form, this material world and the individual existence of the living entities are māyā, or false. This philosophy accepts the authority of Vedic texts but interprets them in such a way as to advance an impersonal conception of the Absolute and deny the personal feature of Godhead. It is known as covered Buddhism, since Buddhism is overtly atheistic.",
    "mīmāṃsā": "A philosophical doctrine that has two divisions: (1) pūrva, or karma-mīmāṃsā, founded by Jaiminī, which advocates that by carrying out the ritualistic duties given in the Vedas, one can attain the celestial planets, and (2) uttara-mīmāṃsā founded by Bādarāyaṇa Vyāsadeva, which deals with the nature of brahma, the Absolute Truth.",
    "mīmāṃsaka": "Philosopher; one who adheres to the mīmāṃsā philosophical doctrine. It usually refers to those who follow the karma-mīmāṃsā of Jaiminī.",
    "mleccha": "(1) Barbarian (2) Those who are unable to properly utter the Vedic mantras.",
    "mokṣa": "Liberation from material bondage.",
    "mudgala ṛṣi": "A sage who used to perform sacrifice on the full moon and dark moon. Once Durvāsā Muni visited him. Pleased by his service attitude, Durvāsā blessed him that he could go to the higher planets in his present body. When the messengers of the demigods came in a celestial airplane to bring him there, he refused to go with them and instead preached to them about temporary nature of the higher planets.",
    "mukti": "Complete emancipation from the bondage of the material energy that is expressed by the false conceptions of ‘I’ and ‘mine’. There are five types of mukti: sārūpya–obtaining the same form as Bhagavān; sāmīpya–living in close proximity to Bhagavān; sālokya–living on the same planet as Bhagavān; sārṣṭi–having the same opulence as Bhagavān;and sāyujya–becoming one with Bhagavān by merging with His bodily effulgence, the brahmajyoti. Of these five, sāyujya is rejected by the Vaiṣṇavas.",
    "muni": "(1) Great sage (2) One who endeavours to approach the Absolute Truth by dint of mental prowess.",
    "nāga": "Divine serpent.",
    "naimittika": "Occasional, causal, incidental.",
    "naimittika-karma": "Occasional religious duties induced by specific circumstances, such as the worship of the forefathers and the demigods in the śrāddha ceremony. A person enters into the realm of exclusive devotion to Śrī Kṛṣṇa only when one completely abandons these activities.",
    "naiṣkarmya": "Freedom from prescribed duty and its reaction; action performed in Kṛṣṇa consciousness for which one suffers no reaction.",
    "nāma": "(1) Name (2) The holy name of Kṛṣṇa, which is Śrī Kṛṣṇa Himself. Nāma is invested with all potencies, with incarnations of Śrī Kṛṣṇa, qualities, paraphernalia, entourage, pastimes, transcendental abode, and so forth, and it is chanted by the devotees in their practice of bhakti.",
    "nāma-saṅkīrtana": "Congregational chanting of the holy names.",
    "nārada": "(See Devarṣi Nārada).",
    "nārada-pañcarātra": "A narrative in five parts: knowledge that gives the supreme truth;knowledge that awards mukti; knowledge that awards bhakti;knowledge that awards mystic perfection and knowledge in the mode of ignorance that is interspersed with numerous mantras, stotras and kavacas.",
    "narādhama": "(1) Lowest of mankind (2) One who gives up the path of bhakti due to lack of faith.",
    "nārāyaṇa": "The four-armed expansion of Śrī Kṛṣṇa and the all-opulent Lord of Vaikuṇṭha.",
    "nava-yogendras": "Nine yogīs in the mellow of servitude who are the nine saintly sons of Ṛṣabhadeva.",
    "ninefold process of bhakti": "Hearing, chanting, remembering, serving the Lord’s lotus feet, worshipping, offering prayers, making friendship with the Lord and surrendering one’s very self to Him.",
    "nirguṇa": "Devoid of material qualities; transcendental to the modes of nature.",
    "nirguṇ ā-bhakti": "Devotion beyond the influence of the three modes.",
    "nirguṇa-brahma": "An erroneous conception of brahma in which it is supposed that the Supreme Absolute Reality is devoid of all qualities. Nirguṇa-brahma actually refers to Śrī Kṛṣṇa, who is free from all material qualities and yet is the master of them.",
    "nirguṇā-śraddhā": "Faith unaffected by the modes of nature.",
    "nirguṇa-tattva": "Scientific knowledge of transcendence.",
    "nirviśeṣa": "Devoid of variety, featureless, without distinction.",
    "nirviśeṣa-brahma": "The featureless aspect of the Supreme Lord.",
    "nirviśeṣa-svarūpa": "Indistinct aspect of Bhagavān; His effulgence.",
    "niṣkāma": "Without selfish desire.",
    "niṣkāma-karma": "Performance of one’s prescribed duty without any desire for the fruits, performed by one who desires jñāna, or liberation.",
    "niṣkāma-karma-yoga": "Selfless performance of one’s prescribed duty in which one unites (yoga) with the Supreme Lord by offering Him the fruit of that work. Although niṣkāma-karma-yoga is certainly conducive to pure devotion, it is not pure devotion in and of itself, because Kṛṣṇa’s happiness and well-being are not the exclusive consideration.",
    "niṣṭhā": "Fixed adherence, or resolve; devotional practice that does not waver at any time. It is the fifth stage in the development of the creeper of devotion.",
    "nistraiguṇya": "Freedom from the three modes of material nature.",
    "nitya": "(1) Eternal (2) Regulated.",
    "nitya-karma": "Daily, or routine, obligatory duties.",
    "oṃkāra": "Sound representation of para-tattva brahma.",
    "oṃ tat sat": "The three words indicating the Supreme Absolute Reality.",
    "pada": "(1) Line of Sanskrit verse (2) abode (3) a foot (4) that which gives evidence in establishing the Supreme Lord.",
    "pāda-sevanam": "Service to the lotus feet of Śrī Bhagavān and His pure devotees; one of the nine limbs of bhakti.",
    "padma": "Lotus.",
    "padma purāṇa": "One of the sāttvika Purāṇas.",
    "pañcarātra": "Group of devotional scriptures that assist in the practice of the principal limbs of bhakti; they cover five topics: (a) the process of cleansing the temple, (b) performing āratika with flowers, incense, etc., (c) worship, bathing, etc. of the deity of Śrī Viṣṇu, (d) the performance of meditation on the holy name and on śrī gāyatrī, (e) recita-tion of verses and prayers, performance of nāma-kīrtana and study of scriptures such as Bhagavad-gītā and Śrīmad-Bhāgavatam, which establish tattva-jñāna. The Pañcarātras are numerous, some of them being prominent in the Gauḍīya Vaiṣṇava lineage: Śrī Nārada-pañcarātra, Śrī Hayaśīrṣa-pañcarātra and Śrī Śāṇḍilya-pañcarātra.",
    "pāṇḍava": "(1) A name for Arjuna (2) A son of King Pāṇḍu.",
    "paṇḍita": "Learned scholar.",
    "pāṇḍu": "The great king of the Kuru dynasty and younger brother of Dhṛtarāṣṭra. He died an untimely death and left his five sons, the Pāṇḍavas, under the care of Dhṛtarāṣṭra.",
    "pāpa": "Sin.",
    "parā-bhakti": "Transcendental bhakti.",
    "parabrahma": "The Supreme Absolute Truth, Śrī Kṛṣṇa; the supreme brahma (See brahma).",
    "para-dharma": "The prescribed duty of another.",
    "parama-dhāma": "Supreme abode.",
    "parama-puruṣa": "Śrī Bhagavān, the supreme enjoyer.",
    "paramātmā": "Supersoul;He who is situated in the hearts of all living entities as a witness and the source of remembrance, knowledge and forgetfulness.",
    "parameśvara": "Supreme controller.",
    "parantapa": "‘Chastiser of the enemy’, Arjuna.",
    "parā-śakti": "Śrī Bhagavān’s transcendental potency, which has three divisions: cit (spiritual), taṭastha (marginal) and māyā (material).",
    "paraśurāma": "Son of Jamadagni and Renukā and the sixth of the ten avatāras of Lord Viṣṇu mentioned in Śrī Daśāvatāra-stotram by Jayadeva Gosvāmī. He slew all the kṣatriyas of the world to give protection to the brāhmaṇas. Literally, rāma–‘one who delights’, paraśu–‘in fighting with the axe’.",
    "para-tattva": "Science of understanding the highest truth.",
    "parokṣa-vāda": "That which remains hidden, or secret, being expressed in an indirect way.",
    "pārtha": "‘Son of Pṛthā’, Arjuna.",
    "piśāca": "Fiend.",
    "pītāmbara": "Yellow dhoṭī.",
    "pitṛ-yāna": "Voyage on the path of the forefathers.",
    "pradhāna": "(See māyā-śakti).",
    "pradhānī-bhūtā-bhakti": "Activities related to bhakti that are mixed with karma and jñāna, bhakti being prominent.",
    "prajāpati": "A living entity empowered to create living beings (prajā) throughout the universe. The chief Prajāpati is Brahmā.",
    "prakāśikā-vṛtti": "‘Commentary that illuminates’.",
    "prakṛti": "Material nature.",
    "prameya-ratnāvalī": "A book by Śrīla Baladeva Vidyābhūṣana, meaning ‘a list of proven truths’.",
    "prāṇa": "(1) Life energy; life-air (2) The in-coming breath (4.27).",
    "praṇāma": "Offering respectful obeisance.",
    "prāṇamaya": "The second of the five stages of consciousness in which one per-ceives life in terms of preservation (13.5).",
    "praṇava": "The syllable that gives life, derived from the Sanskrit verbal root praṇu, to make a reverberating humming of the syllable oṃ (10.25).",
    "prāṇāyāma": "Yogic breathing.",
    "prārabdha-karma": "Results of previous activities that have begun to bear fruit in the form of happiness and distress.",
    "prasāda": "Grace, mercy. Generally refers to remnants of food offered to the deity. It may also refer to other sanctified or blessed articles such as incense, flowers, garlands and clothing.",
    "prasannātmā": "Joyful soul; the first characteristic of one situated in brahma-bhūta, having transcended the gross and subtle bodies manipulated by the three modes of material nature.",
    "pratiṣṭhā": "Support.",
    "pratyāhāra": "Withdrawal of the senses from the sense objects; the fifth step in aṣṭāṅga-yoga.",
    "prema": "Pure love for Kṛṣṇa, which is extremely concentrated, which completely melts the heart, and which gives rise to a deep sense of mamatā, or possessiveness, in relationship to Him.",
    "prema-bhakti": "Stage of bhakti characterized by pure love; the perfectional stage of devotion.",
    "prema-devī": "Goddess of love.",
    "prescribed duty": "The work prescribed by Vedic scriptures in accordance with a person’s natural propensity, either as a brāhmaṇa, kṣatriya, vaiśya or śūdra in one of the four āśramas: brahmacāri, gṛhastha, vānaprastha and sannyāsa; refers to both regular, daily, occupational duties and duties performed on certain occasions.",
    "pūjā": "Worship.",
    "pūjyapāda": "Literally, ‘whose feet are to be revered’; an honorific title.",
    "purāṇas": "Eighteen major and eighteen minor supplements to the Vedas, written by Śrīla Kṛṣṇa Dvaipāyana Vedavyāsa.",
    "puru": "Son of of Mahārāja Yayāti who accepted his father’s request to exchange his old age for his youth (Śrīmad-Bhāgavatam, 9.18–20).",
    "puruṣa": "Enjoyer;refers to either the living entity or the Supreme Lord.",
    "puruṣa-avatāra": "Śrī Kṛṣṇa’s three expansions that create the cosmic manifestation for the upliftment of the rebellious living entities: Kāraṇod-akaśāyī Viṣṇu, Garbhodakaśāyī Viṣṇu and Kṣīrodakaśāyī Viṣṇu (Śrīmad-Bhāgavatam 1.3.1–3 and 2.6.39–42).",
    "puruṣa-sūkta": "A hymn from the Ṛg-Veda glorifying the Supersoul.",
    "puruṣottama": "Supreme enjoyer.",
    "rāga": "(1) Deep attachment for Kṛṣṇa, permeated by spontaneous and intense absorption in the object of one’s affection (2) A deep and overpowering thirst for the object of one’s affection.",
    "rāga-mārga": "Path of spontaneous attachment.",
    "rahasya": "Confidential, or secret.",
    "rājasika": "Of the material mode of passion.",
    "rajo-guṇa": "Mode of passion.",
    "rākṣasa": "Flesh-eating demon, generally endowed with mystic powers.",
    "rāmānujācārya": "Ācārya of the Śrī sampradāya and propounder of qualified monism (viśiṣṭādvaita-vāda) which states that although all of the energies of God are one, each maintain its speciality (vaiśiṣṭya).",
    "rasa": "The exact English equivalent is untranslatable, but is herein rendered as ‘mellow quality’. It is the spiritual trans-formation of the heart which takes place when the perfected state of love for Kṛṣṇa, known as rati, is converted into heart-melting emotions by combining with various types of transcendental ecstasies.",
    "rasika-rañjana": "Lit, ‘that which pleases those who relish transcen-dental mellows’, Śrīla Bhaktivinoda Ṭhākura’s Bengali translation-commentary of Śrīmad Bhagavad-gītā.",
    "raso vai saḥ": "Literally, ‘He, Bhagavān, is certainly the embodiment of all rasa’.",
    "rati": "(1) Attachment, fondness (2) A stage in the development of bhakti which is synonymous with bhāva.",
    "ṛtvik": "Priest who performs a sacrifice on someone’s behalf.",
    "rudra": "One of the eleven expansions of Lord Śiva.",
    "rūpā gosvāmī": "The foremost follower of Śrī Caitanya Mahāprabhu. His mission was to show living entities the path to their highest auspiciousness, service to Śrī Śrī Rādhā-Kṛṣṇa in the mood of the damsels of Vraja within whom the acme of spontaneous devotion resides eternally and inherently. The three commentators of this Gītā are purely in the line of Śrīla Rūpa Gosvāmī and dedicated to disseminating his teachings.",
    "śabda": "Sound;word.",
    "śabda-brahma": "(1) Imports of Vedic scripture (2) Sound incarnation of the Absolute Truth.",
    "sac-cid-ānanda": "Eternality, cognizance and bliss.",
    "sad-guru": "Bona fide spiritual master; spiritual preceptor who follows sat (the pure path of the sādhus as described within scripture and as delivered through paramparā).",
    "sādhaka": "One who performs regulated spiritual discipline to achieve a specific goal.",
    "sādhana": "Method, or practice adopted to accomplish a specific goal. Without sādhana one cannot obtain the goal. Sādhana corresponds to various goals: those who desire material enjoyment adopt the path of karma as their sādhana, those who desire liberation adopt the path of jñāna, and those who aspire for the eternal loving service of Śrī Kṛṣṇa adopt the path of bhakti, which involves the spiritual practices of hearing, chanting and so on.",
    "sādhu": "Highly advanced devotees who embody devotion to the Supreme Lord. In a general sense this refers to any saintly, or religious person.",
    "sādhu-saṅga": "The association of saintly persons; the second stage in the development of the creeper of bhakti and the most important factor for advancement in bhakti.",
    "sādhya": "Object, or goal, for which one undergoes a corresponding practice.",
    "saguṇa": "(1) With material qualities (2) Possessing transcendental qualities.",
    "saguṇa-brahma": "The Absolute Truth endowed with all transcendental qualities.",
    "sakāma": "With desire.",
    "sakāma-bhakti": "Devotion performed with material desires.",
    "sakāma-karma": "Actions performed with a desire to taste the material result.",
    "sakāma-karmī": "One who accepts a regulated life but maintains material desires.",
    "sakhā": "Male friend, companion or atten-dant. In the Gītā, this refers to Arjuna.",
    "sakhya-bhāva": "Mood of friendship with Kṛṣṇa.",
    "śakti": "Potency, or energy.",
    "śaktimān": "Possessor of potency, Śrī Kṛṣṇa.",
    "śaktyāveśa-avatāra": "Empowered incarnation; a living entity who, in submission to Bhagavān, becomes empowered (āveṣa) by Him to act powerfully on His behalf.",
    "sālokya": "The liberation of attaining the same planet as Śrī Bhagavān.",
    "sama-darśī": "One who possesses equal vision.",
    "samādhi": "Concentration of the mind; meditation or deep trance, either on Paramātmā or Kṛṣṇa’s pastimes.",
    "sampradāya": "Unbroken disciplic successive line transmitted from guru to disciple. Mantra is only effective when received in a bona fide sampradāya, of which there are four: Brahma, Śrī, Rudra and Sanaka.",
    "samprajñāta-samādhi": "Samādhi in which one is conscious of the difference between knowledge, the object of knowledge and the knower.",
    "saṃskāra": "(1) Sacred, or sanctifying, ceremony (2) Reformation or training of the mind (3) Impression on the mind of any previous purificatory act in this or in prior births.",
    "saṃvit": "The potency that bestows transcendental knowledge of Śrī Bhagavān.",
    "sanātana": "Eternal.",
    "sanātana gosvāmī": "One of the six Gosvāmīs of Vṛndāvana; elder brother of Rūpa Gosvāmī and author of numerous literatures, the most prominent of which are the Hari-bhakti-vilāsa and Bṛhad-bhāgavatāmṛta.",
    "saṅga": "Association.",
    "sañjaya": "The charioteer and minister of King Dhṛtarāṣṭra. He received divine vision by the mercy of Vyāsadeva and was therefore able to narrate all the events of the war to Dhṛtarāṣṭra.",
    "saṅkalpa": "The mind’s function of acceptance and determination.",
    "śaṅkarācārya": "A propagator of māyāvāda, or impersonalism, under-stood to be an incarnation of Lord Śiva.",
    "sāṅkhya": "(1) Analytically discriminat-ing between spirit and matter (2) The path of bhakti practised by analyzing the twenty-four universal elements.",
    "sāṅkhya-yoga": "Yoga that gives analytical knowledge about scientific knowledge of the soul, the Supersoul and inert objects.",
    "saṅkīrtana-yajña": "Congregational chanting of the Lord’s holy names; the yuga-dharma for the age of Kali.",
    "sannyāsa": "(1) Completely giving up the results of one’s activities (2) The fourth stage of life in the varṇāśrama system. There are four stages of sannyāsa: (a) Kūtīcaka. He resides in a hut (kūtīr) and accepts alms from a family or āśrama till his sādhana reaches maturity; (b) Bahūdaka. He then travels on pilgrim-age and bathes in many (bahu) waters (udakas), practising detachment through dependence on Bhagavān; (c) Parivrājak. When transcendental knowledge arises in his heart, he preaches his realizations to everyone, in every village; (d) Parama-haṃsa. By full absorption in kṛṣṇa-kathā, kṛṣṇa-tattva and kṛṣṇa-kīrtana, he becomes fully mature and the swan (haṃsa) of his mind always dives and surfaces in Śrī Śrī Rādhā-Kṛṣṇa’s ever fresh pastimes.",
    "sannyāsī": "(1) One in the renounced order of life, which is the highest order in the varṇāśrama-dharma system (2) One who renounces the fruits of one’s activity.",
    "śānta-rasa": "Mellow of neutrality in which one appreciates the greatness of Śrī Bhagavān, just as a Paramātma-realized yogī does. It is one of the primary rasas.",
    "śaraṇāgati": "Surrender. The six symptoms of surrender (śaraṇa) are (a) acceptance of anything that fosters the growth of the creeper of devotion, (b) avoidance of anything that hinders that growth, (c) the firm faith that Śrī Śrī Rādhā-Kṛṣṇa will always extend the protective umbrella of Their lotus feet over Their devoted servants, (d) acceptance of Their Lordships as one’s exclusive guardians, (e) submissive offering of one’s full self at Their lotus feet and (f) always feeling one’s self lowly and humble.",
    "sārārtha-varṣiṇī": "Sāra means ‘essence’ or ‘cream’, artha means ‘meaning’, varṣiṇī means ‘shower’. Literally, ‘a shower of the essential meanings’.",
    "sarva-svarūpa": "Śrī Kṛṣṇa, who manifests to the worshipper in whatever form the worshipper desires to see Him.",
    "śāstra": "Vedic scripture; derived from the Sanskrit verbal root śās (to govern, command).",
    "sat": "Eternal, pure, godly. It is used to describe the Absolute Truth. Vrajendra-nandana Śrī Kṛṣṇa is the complete sat entity. It also refers to His abodes, incarnations, devotees, the bona fide guru, etc.",
    "ṣaṭaka": "Literally, ‘a group of six’.",
    "sattamaḥ": "Best of godly men.",
    "sattva-guṇa": "Mode of goodness (See rajo-guṇa and tamo-guṇa).",
    "sāttvika": "Of the mode of goodness.",
    "satya": "Truth.",
    "satya-saṅkalpa": "Name of Bhagavān meaning that His resolve (saṅkalpa) becomes fact (satya).",
    "śaunaka": "The head of the great sages at Naimisāraṇya who were present when Śrīla Sūta Gosvāmī spoke Śrīmad-Bhāgavatam to Parīkṣit Mahārāja.",
    "saviśeṣa": "With features and unique qualities.",
    "sāyujya-mukti": "The liberation of merging one’s existence with the effulgence of Bhagavān. Since there is no facility to render service to Kṛṣṇa in this liberation, it is never accepted by Vaiṣṇavas, even if offered by Śrī Bhagavān, Himself.",
    "siddha": "Perfection.",
    "siddhānta": "Conclusive truth; authoritative principle of scripture.",
    "siddhi": "Perfection. There are eight mystic siddhis achieved by aṣṭāṅga-yogīs.",
    "śikṣā": "Instruction.",
    "śikṣā-guru": "Guru who instructs one on the path of bhajana.",
    "śiśupāla": "A demon in Kṛṣṇa’s pastimes.",
    "śiṣya": "Disciple. It is derived from the verbal root śās (to command) indicating that a disciple must accept śrī guru’s order as his very life.",
    "śiva": "(1) Auspicious (2) The destroyer of the material creation and the presiding deity of the mode of ignorance.",
    "skanda purāṇa": "Purāṇa written for those in the mode of passion.",
    "śloka": "Verse in Sanskrit composition.",
    "smaraṇam": "Remembrance of the names, forms, qualities and pastimes of Śrī Kṛṣṇa; the third step of the ninefold process of bhakti.",
    "smārta": "(1) One who rigidly adheres to the Smṛtis, being overly attached to external rituals without comprehending the underlying essence, or conclusion, of śāstra. (2) The brāhmaṇa followers of Śaṅkara.",
    "smṛti": "That which is remembered. The body of sacred literature which remem-bers Śrī Bhagavān (in contradistinction to Śruti, which is directly heard by or revealed to the ṛṣis). They include the six Vedāṅgas, the dharma-śāstras such as Manu-saṃhita, the Purāṇas, and the Itihāsas (histories).",
    "soma-rasa": "Nectar drunk by the demigods that grants them relative immortality.",
    "śraddhā": "Faith in the statements of scripture awakened when one has accumulated pious devotional activities over many births or by the association and mercy of a pure Vaiṣṇava; the first manifestation of the creeper of devotion. The inner essence of the seed of śraddhā is the conception implanted within the disciple’s heart to serve Śrī Śrī Rādhā-Kṛṣṇa in a particular capacity.",
    "śrāddha": "Ceremony in honour of and for the benefit of deceased relatives.",
    "śravaṇam": "Hearing;the first of the ninefold process of bhakti.",
    "śrī": "(1) An honorific prefix to a name (2) Beauty (3) Lakṣmī, the goddess of fortune (4) Śrīmatī Rādhārāṇī.",
    "śrīdhara svāmīpāda": "Author of Śrīmad-Bhāgavatam commentary accepted by Śrī Caitanya Mahāprabhu.",
    "śrīmad-bhāgavatam": "Crest jewel of Vedic literatures and the nectarean ripened fruit of the tree of Vedic knowledge. It is the spotless Purāṇa, which offers no fruitive motivation for the performance of pious deeds, since it only encourages unmotivated devotion (See Vedānta).",
    "śruti": "(1) That which is heard (2) Reve-lation, as distinguished from Smṛti (3) Infallible knowledge that descends in disciplic succession. It is the body of literature that was directly manifest by the Supreme Lord, in other words, the original four Vedas (also known as nigama) and the Upaniṣads.",
    "sthita-prajña": "One whose intelligence is fixed in self-realization.",
    "stuti": "Praise, or prayers, in glorification of Śrī Bhagavān.",
    "sudāmā vipra": "Brāhmaṇa friend of Śrī Kṛṣṇa.",
    "sudarśana cakra": "Invincible disc weapon of Śrī Bhagavān.",
    "śuddha-bhakti": "Pure devotion.",
    "śuddha-sattva": "Pure, transcen-dental goodness (See viśuddha-sattva).",
    "śūdra": "Labourer or artisan.",
    "su-durācāra": "One who commits the most abominable actions (9.30).",
    "sukha": "Happiness.",
    "śukrācārya": "Guru of the demons.",
    "sukṛti": "Spiritual merit.",
    "sumeru": "The golden mountain on which the Ganges waters fall.",
    "śūnyavādī": "(1) Voidist (2) Follower of the teachings of Buddha.",
    "sūrya": "Sun-god.",
    "sūta gosvāmī": "The great sage who spoke Śrīmad-Bhāgavatam in Naimisāraṇya.",
    "sūtras": "Concise aphorisms, which contain compressed knowledge for easy learning and remembrance.",
    "sva-bhāva": "One’s nature, disposition.",
    "sva-dharma": "One’s prescribed duty; occupation according to one’s nature.",
    "svāṃśa": "Śrī Bhagavān’s plenary portions.",
    "svarūpa": "The eternal nature and iden-tity of the self; one’s transcendental form.",
    "svarūpa-śakti": "Internal potency of Śrī Bhagavān, superior to His marginal and external potencies. It has three divisions: sandhinī (existence), samvit (knowledge) and hlādinī (transcendental bliss).",
    "svayam bhagavān śrī kṛṣṇa": "Śrī Kṛṣṇa, the original Personality of Godhead, from whom all His incarnations emanate.",
    "svayaṃvara": "Contest to win the hand of a princess in marriage, wherein the princess herself (svayam) chooses (vara).",
    "tāmasika": "Related to the material mode of ignorance.",
    "tamo-guṇa": "Material mode of ignorance, or darkness.",
    "tapa": "Austerity.",
    "tapasyā": "Austerity.",
    "tapo-yajña": "Sacrifice of performing austerities.",
    "tat": "Supreme Spirit (brahma); the cause of the universe.",
    "taṭastha-śakti": "Literally, taṭa–‘mar-ginally’, stha–‘situated’, śakti–energy. In other words, it is the marginal energy of Śrī Bhagavān which manifests the living entities.",
    "tattva": "Fundamental truth.",
    "tattva-darśī": "One who has realized the Absolute Reality.",
    "tattva-jñāna": "Conclusive knowledge of fundamental truths.",
    "tattva-vit": "Conversant with categorical knowledge of the Truth, such as guru-tattva, māyā-tattva and īśvara-tattva.",
    "ṭīkā": "Commentary.",
    "tretā-yuga": "Second of the four yugas: Satya, Tretā, Dvāparā and Kali.",
    "tyāga": "Renunciation of possessiveness.",
    "uddhava": "Advisor, minister and close friend of Sri Kṛṣṇa in Dvārakā; a disciple of Bṛhaspati; a jñāna-miśra-bhakta.",
    "upaniṣads": "108 principle philosophical treatises that appear within the Vedas.",
    "upāsaka": "Worshipper.",
    "upāsanā": "Spiritual practices.",
    "uttama-bhāgavata": "Highest level of devotee.",
    "vairāgya": "(1) Detachment from this world (2) Spiritual discipline involving voluntary austerities to achieve detachment from the objects of the senses.",
    "vaiṣṇava": "One in whose heart and mind only Śrī Viṣṇu, or Śrī Kṛṣṇa, resides; a devotee of Śrī Kṛṣṇa. Literally, ‘belonging to Lord Viṣṇu’.",
    "vaiśya": "Agriculturalists, cowherds, businessmen.",
    "vāntāśī": "One who returns to worldly sense enjoyment after taking sannyāsa. Literally, vānta–‘vomit’, āśī–‘eater’.",
    "varāha purāṇa": "One of the sāttvika Purāṇas.",
    "varṇa": "Occupational division, or caste, which is ascertained according to one’s nature.",
    "varṇāśrama-dharma": "The Vedic social system, which arranges society into four occupational divisions based on a person’s qualities and four stages of spiritual development (See prescribed duty).",
    "varuṇa": "God of the waters.",
    "vāsudeva": "The son of Vasudeva, Śrī Kṛṣṇa.",
    "vasus": "Eight demigods.",
    "veda": "Knowledge, or the four primary books of knowledge compiled by Śrīla Vyāsadeva: the Ṛg Veda, Sāma Veda, Atharva Veda and Yajur Veda.",
    "vedāṅga": "Six auxiliary portions of the Vedas: (a) Śikṣā, proper pronunciation and articulation of Vedic Sanskrit, (b) chanda, rhythmic metres for chanting ślokas, (c) vyākaraṇa, grammar, (d) nirukta, an explanation of difficult Vedic words, (e) jyotiṣa, astrology, (f) kalpa, the ceremonial process of Vedic ceremonies for sacrifice.",
    "vedānta": "Literally, veda–‘Vedic knowledge’, anta–‘conclusion’. The Upaniṣads are the latter portion of the Vedas, and the Vedānta-sūtra summarizes the philosophy of the Upaniṣads in concise statements. Therefore the word ‘Vedānta’ especially refers to the Vedānta-sūtra.",
    "vedānta-āc ārya": "A most exalted teacher of Vedānta. The vedānta-ācārya in the Gauḍīya sampradāya is Śrī Baladeva Vidyābhūṣaṇa",
    "vedānta-sūtra": "(See Brahma-sūtra).",
    "vibhinnāṃśa": "Separated parts of Bhagavān, the living entities.",
    "vibhūti": "Bhagavān’s divine opulences.",
    "vibhūti-yoga": "Yoga through compre-hending Śrī Kṛṣṇa’s divine glories.",
    "vidvad -rañjana": "Lit, ‘that which pleases the wise’, Śrīla Bhaktivinoda Ṭhākura’s Bengali translation-commentary on Śrīmad Bhagavad-gītā.",
    "vidvat-pratīti": "Perception based on transcendental knowledge.",
    "vidyā": "Knowledge.",
    "vijñāna": "(1) Realization of divine knowledge (2) Realization of Śrī Kṛṣṇa’s mādhurya (sweetness).",
    "vijñāna-maya": "Fourth of the five stages of consciousness in which one is conscious of the soul (13.5).",
    "vikarma": "Action that disobeys Vedic injunction; sinful activity.",
    "vipra": "A learned brāhmaṇa.",
    "virocana": "The demon son of Prahlāda Mahārāja and the father of Bali Mahārāja.",
    "vismaya": "Wonder.",
    "vismaya-rasa": "Mellow of astonishment.",
    "viṣṇu": "Literally, viś–‘pervading’, nu–‘person’. One who is all-pervasive, the Supreme Lord of the cosmos who presides over the mode of goodness.",
    "viṣṇu-tattva": "Categorical knowledge of the unlimited expansions of Viṣṇu.",
    "viśuddhā-bhakti": "Exclusive, supremely pure devotion, in which one has no attachment to anyone but Bhagavān.",
    "viśuddha-sattva": "State of unalloyed goodness that is beyond the influence of material nature.",
    "viśvanātha cakravartī ṭhākura": "A prominent ācārya of Gauḍīya Vaiṣṇavism who authored many books and commentaries, including this Sārārtha-varṣiṇī commentary on Śrīmad Bhagavad-gītā.",
    "viśvarūpa": "Universal form.",
    "viśvarūpa-upāsanā": "Worship of the universal form.",
    "vrajabhūmi": "Vṛndāvana, Śrī Kṛṣṇa’s eternal abode.",
    "vrajendra-nandana": "The son of the king of Vraja, Śrī Kṛṣṇa.",
    "vrata": "Vow undertaken for self-purification and spiritual benefit.",
    "vṛṣṇis": "Kings of the Yadu dynasty.",
    "vyāsa": "Vedavyāsa, the literary incarnation of the Lord and the compiler of Vedas, Purāṇas, Upaniṣads, Brahma-sūtra and Śrīmad-Bhāgavatam.",
    "yādava": "Śrī Kṛṣṇa, the best of the Yādu dynasty.",
    "yajña": "(1) Sacrifice in which a deity is propitiated by the chanting of prayers and mantras and the offering of ghee into the sacred fire (2) Any kind of intense endeavour that is directed at achieving a particular goal.",
    "yakṣa": "Ghost, or spirit.",
    "yaśodā-nandana": "Son of Yaśodā, Śrī Kṛṣṇa.",
    "yavana": "Barbarian, i.e. one who does not follow a pure lifestyle.",
    "yoga": "Spiritual discipline practised to become linked with the Supreme.",
    "yogamāyā": "The internal potency of Bhagavān that arranges and enhances all His pastimes.",
    "yoga-miśrā-bhakti": "Bhakti mixed with yoga, where bhakti predominates.",
    "yogeśvara": "The supreme master of mystic power, Śrī Kṛṣṇa.",
    "yogī": "(1) One whose heart remains connected with Śrī Bhagavān (2) One who endeavours for spiritual perfection.",
    "yuga": "One age within the cycle of the universal four ages, named Satya, Tretā, Dvāpara and Kali.",
    "yuga-avatāra": "Incarnations of the Lord who teach the particular religion for each yuga."
};